<?php

class PageModel
{
    public static function getStandartTheme()
    {
        $db = Db::connect();

        $query = "SELECT themes.file FROM themes WHERE themes.id = 1";
        $result = $db->query($query)->fetch(PDO::FETCH_ASSOC);

        return $result['file'];
    }

    public static function getDictionary($lang)
    {
        $dictionary = [
            'eng' =>
            [
                'registration' => 'Registration',
                'theme' => 'Theme',
                'download' => 'Download',
                'themeName' => 'Theme name...',
                'add' => 'Add',
                'change' => 'Change',
                'login' => 'Login',
                'email' => 'Email',
                'about' => 'About',
                'role' => 'Role',
                'user' => 'User',
                'moderator' => 'Moderator',
                'admin' => 'Admin',
                'update' => 'Update',
                'delete' => 'Delete',
                'dashboard' => 'Dashboard',
                'welcome' => 'You are welcome',
                'events' => 'Events',
                'suggestEvent' => 'Suggest event',
                'aboutUs' => 'About us',
                'logIn' => 'Log In',
                'logOut' => 'Log Out',
                'moderatorPanel' => 'Moderator panel',
                'adminPanel' => 'Admin panel',
                'profile' => 'Profile',
                'password' => 'Password',
                'passwordConfirm' => 'Confirm password',
                'question' => 'Question',
                'answersNum' => 'Number of answers',
                'answer' => 'Answer',
                'create' => 'Create',
                'title' => 'Title',
                'header' => 'Header',
                'content' => 'Content',
                'post' => 'Post',
                'posts' => 'Posts',
                'quizes' => 'Quizes',
                'users' => 'Users',
                'themes' => 'Themes',
                'dropHere' => 'Drop photos here to download',
                'postedOn' => 'Posted on',
                'by' => 'by',
                'leaveComment' => 'Leave a comment',
                'save' => 'Save',
                'blogSearch' => 'Event search',
                'lang' => 'Language'
            ],
            'rus' =>
            [
                'registration' => 'Регистрация',
                'theme' => 'Тема',
                'download' => 'Загрузка',
                'themeName' => 'Имя темы...',
                'add' => 'Добавить',
                'change' => 'Изменить',
                'login' => 'Логин',
                'email' => 'Электронный адресс',
                'about' => 'Про себя',
                'role' => 'Роль',
                'user' => 'Пользователь',
                'moderator' => 'Модератор',
                'admin' => 'Администратор',
                'update' => 'Обновить',
                'delete' => 'Удалить',
                'dashboard' => 'Панель управления',
                'welcome' => 'Добро пожаловать',
                'events' => 'События',
                'suggestEvent' => 'Предложить событие',
                'aboutUs' => 'Про нас',
                'logIn' => 'Войти',
                'logOut' => 'Выйти',
                'moderatorPanel' => 'Панель модератора',
                'adminPanel' => 'Панель администратора',
                'profile' => 'Профиль',
                'password' => 'Пароль',
                'passwordConfirm' => 'Подтверждение пароля',
                'question' => 'Вопрос',
                'answersNum' => 'Уоличество вопросов',
                'answer' => 'Ответ',
                'create' => 'Создать',
                'title' => 'Заглавие',
                'header' => 'Заголовок',
                'content' => 'Содержание',
                'post' => 'Пост',
                'posts' => 'Посты',
                'quizes' => 'Опросы',
                'users' => 'Пользователи',
                'themes' => 'Темы',
                'dropHere' => 'Перетащите фото сюда для загрузки',
                'postedOn' => 'Добавлено',
                'by' => 'пользователем',
                'leaveComment' => 'Оставить комментарий',
                'save' => 'Сохранить',
                'blogSearch' => 'Поиск события',
                'lang' => 'Язык'
            ],
            'ukr' =>
                [
                    'registration' => 'Регістрація',
                    'theme' => 'Тема',
                    'download' => 'Загрузка',
                    'themeName' => 'Ім`я теми...',
                    'add' => 'Додати',
                    'change' => 'Змінити',
                    'login' => 'Логін',
                    'email' => 'Електронна адреса',
                    'about' => 'Про себе',
                    'role' => 'Роль',
                    'user' => 'Користувач',
                    'moderator' => 'Модератор',
                    'admin' => 'Адміністратор',
                    'update' => 'Обновити',
                    'delete' => 'Видалити',
                    'dashboard' => 'Панель керування',
                    'welcome' => 'Ласкаво просимо',
                    'events' => 'Події',
                    'suggestEvent' => 'Запропонувати подію',
                    'aboutUs' => 'Про нас',
                    'logIn' => 'Вхід',
                    'logOut' => 'Вихід',
                    'moderatorPanel' => 'Панель модератора',
                    'adminPanel' => 'Панель адміністратора',
                    'profile' => 'Профіль',
                    'password' => 'Пароль',
                    'passwordConfirm' => 'Підтвердження пароля',
                    'question' => 'Питання',
                    'answersNum' => 'Кількість питань',
                    'answer' => 'Відповідь',
                    'create' => 'Створити',
                    'title' => 'Назва',
                    'header' => 'Заголовок',
                    'content' => 'Зміст',
                    'post' => 'Пост',
                    'posts' => 'Пости',
                    'quizes' => 'Опитування',
                    'users' => 'Користувачі',
                    'themes' => 'Теми',
                    'dropHere' => 'Перетягніть фото сюди для завантаження',
                    'postedOn' => 'Додано',
                    'by' => 'користувачем',
                    'leaveComment' => 'Залишити коментвр',
                    'save' => 'Зберегти',
                    'blogSearch' => 'Пошут подій',
                    'lang' => 'Мова'
                ],
        ];
        return $dictionary[$lang];
    }
}